### ISSUE TITLE
Possible integrate with infinite scroll or push for more

### ISSUE THREAD

**Issue by doodirock** [jchristopher/searchwp-live-ajax-search#27]
Wonder if anyway has implemented a way to add more search result on scroll or click for more?  Looking to use this on a project in the near future.

**Comment by jchristopher** [comment]
Hi there, you can fully customize the results: https://searchwp.com/extensions/live-search/#customizing-results and to integrate some sort of 'more' link functionality you'd need to implement your own calls to SearchWP (or `WP_Query`) and pass along the proper pagination argument to pull in the next set.

It'd be a bit of a manual process since nothing is built in to do that, but the other option would be having the 'more' link link directly to your standard set of search results, but have that be paginated, e.g.

http://example.com/?s=test&paged=2
