### ISSUE TITLE
Move JS and CSS to footer

### ISSUE THREAD

**Issue by creativeslice** [jchristopher/searchwp-live-ajax-search#58]
Currently the CSS and JS files are being loaded in the head of the page which is incurring a penalty with Google PageSpeed.

/wp-content/plugins/searchwp-live-ajax-search/assets/styles/style.css
/wp-content/plugins/searchwp-live-ajax-search/assets/javascript/searchwp-live-search.min.js

What's the best way to move this to the footer with the rest of our scripts?

**Comment by jchristopher** [comment]
You'll need to dequeue each and then enqueue them manually, e.g.

```php
// Dequeue SearchWP Live Ajax Search CSS and JS
function my_remove_searchwp_live_search_theme_css() {
	wp_dequeue_style( 'searchwp-live-search' );
	wp_dequeue_script( 'swp-live-search-client' );
}
add_action( 'wp_enqueue_scripts', 'my_remove_searchwp_live_search_theme_css', 20 );

// TODO: enqueue both assets as you want
```

**Note:** you will need to enqueue that style handle and that script handle on your end.

**Comment by timbowen** [comment]
Any chance you'll be updating the enqueue method so we can load JS and CSS in the footer and not incur a speed penalty? The manual method does work, however this means whenever you make updates to the plugin it has a change to break our implementation.

Thanks!

**Comment by jchristopher** [comment]
Hi Tim, it's not on the backlog at the moment due to time constraints on my end but the hooks referenced above shouldn't (ever?) need to be updated even if the plugin gets updated, since the hooks are in your code which the plugin doesn't touch. If you happen to have some spare time to put together a PR that'd be great as well!

**Comment by timbowen** [comment]
The hooks above work great for removing the code. The problem is that we need to add it back in the footer and that is where things will break if we just pull your code into our regular build process.

Or am I missing something on how this works?

**Comment by jchristopher** [comment]
Is your end goal to merge/concat the plugin JavaScript and CSS into your build process? Or is it to just output the plugin-registered JavaScript and CSS in the footer?

**Comment by timbowen** [comment]
The method we're doing now is to add your JS/CSS code right into the theme JS/CSS so it loads in the footer. This is nice because it combines the files, however it's not a good method for friendliness.

The method I'd prefer is if we could load your JS and CSS files exactly like we're doing now EXCEPT load them in the footer instead of the header. That's how plugins like Gravity Forms do it and it allows us to maintain a fast page speed while not breaking things down the road when the plugin updates.

Is this second method possible? Or should we just continue to combine your files as part of our theme for now?

**Comment by jchristopher** [comment]
I wouldn't suggest combining the files, no. In the snippet above, the last line reads

```php
// TODO: enqueue both assets as you want
```

Which (if your end goal is to have WordPress output the `<script>` and `<style>` in the footer) would be to re-enqueue those assets in the footer, e.g.

```php
function my_enqueue_searchwp_live_search_theme_css() {
	wp_enqueue_style( 'searchwp-live-search' );
	wp_enqueue_script( 'swp-live-search-client' );
}

add_action( 'wp_footer', 'my_enqueue_searchwp_live_search_theme_css' );
```

So the full implementation, to prevent the main plugin from enqueueing in the `<head>` and instead enqueue in `wp_footer` would be:

```php
function my_remove_searchwp_live_search_theme_css() {
	wp_dequeue_style( 'searchwp-live-search' );
	wp_dequeue_script( 'swp-live-search-client' );
}

add_action( 'wp_enqueue_scripts', 'my_remove_searchwp_live_search_theme_css', 20 );

function my_enqueue_searchwp_live_search_theme_css() {
	wp_enqueue_style( 'searchwp-live-search' );
	wp_enqueue_script( 'swp-live-search-client' );
}

add_action( 'wp_footer', 'my_enqueue_searchwp_live_search_theme_css' );
```

So that way you're working directly with the JS and CSS that the plugin has registered, you're just telling WordPress to enqueue it at a different point.

**Comment by timbowen** [comment]
You are amazing.
