### ISSUE TITLE
Incompatibility with Relevanssi custom excerpt

### ISSUE THREAD

**Issue by KEYwebdesign** [jchristopher/searchwp-live-ajax-search#80]
I am working with Relevanssi and SearchWP Live Ajax Search and I just found an incompatibility, namely the "Custom Excerpt" that Relevanssi makes from custom fields (post meta).

In the regular search result page, these custom excerpts are shown, but in the Live Search results, these custom search snippets don't work.

I use the search-results.php template in my theme, in which I have the "the_excerpt()" php function, but nothing shows up in the results. Is there any way to get this to work?

**Comment by msaari** [comment]
The live search is not really supposed to show excerpts in the first place, it's supposed to just show the title. The search results template has no effect on the live search dropdown.

**Comment by KEYwebdesign** [comment]
The /searchwp-live-ajax-search/search-results.php file IS the template file for the Live Search dropdown, so yes it does have effect.

Anyone else ideas about this?

**Comment by msaari** [comment]
Actually, I do have something useful for this. This is a Relevanssi issue. Relevanssi doesn't want to create excerpts in admin context, and doing AJAX is in admin context – thus no excerpts in the AJAX search.

I can modify Relevanssi so that it allows excerpts in admin context when doing AJAX, then you'll get Relevanssi-generated excerpts for live search.

@jchristopher, you can close this issue here, this is not a SearchWP Live Ajax Search issue.

**Comment by jchristopher** [comment]
Awesome, thanks @msaari!

**Comment by KEYwebdesign** [comment]
@msaari What would this modification mean exactly?

**Comment by msaari** [comment]
Once this fix is in place https://github.com/msaari/relevanssi/commit/6879ad6baaa1ca4125c832cbdb2ab1ec3977899b in version 4.0.10 (you can make the change in /lib/search.php now, if you want it immediately, it's just one line), Relevanssi will be able to generate excerpts in AJAX searches, and if your template in SearchWP Live Ajax Search includes `the_excerpt()`,  it'll show a Relevanssi-generated excerpt.
